### ISSUE TITLE
Two-way bindings on state charts

### ISSUE THREAD

**Issue by mattpocock** [mattpocock/figma-xstate-plugin#4]
> The below is ripped from #2 

Since in a real life project the requirements/specs may change, it would also be nice if this plugin could update a Figma document with new frames while retaining the old ones if a machine is modified and re-imported.

As a stretch goal, it would be awesome if there was a two-way binding to the state chart, so you could visually update it from within Figma. I suspect David is working on a visual tool already, but allowing designers to actually build out/augment state charts from inside Figma would be a huge boon.

**Comment by Jayphen** [comment]
I think this could be achieved by enforcing a strict naming scheme.

For example, frames that are part of the machine must be prefixed with `STATE:`. Events must named `EVENT:EVENT_NAME:TARGET` or `EVENT:EVENT_NAME:[TARGET:COND][TARGET:COND]`.

**Comment by Jayphen** [comment]
I've actually just partially implemented this on my repo now!

**Comment by mattpocock** [comment]
Nice! This is neat.
